language: node_js

sudo: required
dist: trusty

services:
  - docker

before_install:
  - curl -L https://github.com/docker/compose/releases/download/1.4.2/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo rm /usr/local/bin/docker-compose
  - sudo mv docker-compose /usr/local/bin

install:
  - sudo apt-add-repository "deb http://download.virtualbox.org/virtualbox/debian trusty contrib"
  - wget -q https://www.virtualbox.org/download/oracle_vbox.asc -O- | sudo apt-key add -
  - sudo apt-get update -q
  - sudo apt-get -y install -q linux-headers-3.19.0-30-generic --fix-missing
  - sudo apt-get -y install -q virtualbox-5.0 --fix-missing
  - sudo wget -nv https://releases.hashicorp.com/vagrant/1.8.1/vagrant_1.8.1_x86_64.deb
  - sudo dpkg -i vagrant_1.8.1_x86_64.deb

script:
  - docker-compose -f docker-compose.yml pull
  - docker-compose -f docker-compose.yml rm -f
  - docker-compose -f docker-compose.yml up -d
  - sleep 30
  - curl -vv http://localhost:8080/
  - docker-compose -f docker-compose.yml down
  - docker-compose -f docker-compose.yml rm -f
  - docker rm $(docker ps -a -q -f)
  - docker rmi $(docker images -q)
  - vagrant up
  - sleep 30
  - curl -vv http://localhost:8080/
